In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [5]:
print(arr + 1)

[2 3 4 5 6]


In [9]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
print(arr2d.ndim)

2


In [19]:
print(arr.ndim)

1


In [20]:
print(arr[3])


4


In [24]:
arr2d[0,1]

np.int64(2)

In [26]:
print(arr[-2])


4


In [27]:
arr2 = arr
arr2[0] = 10

In [29]:
print('arr2', arr2)
print('arr', arr)
arrCopy = arr.copy()
arrCopy[0] = 40
print('arrCopy', arrCopy)
print('arr', arr)

arr2 [10  2  3  4  5]
arr [10  2  3  4  5]
arrCopy [40  2  3  4  5]
arr [10  2  3  4  5]


In [30]:
for x in arr:
  print(x)


10
2
3
4
5


In [32]:
np.sort(arr)

array([ 2,  3,  4,  5, 10])

In [33]:
arr * 3


array([30,  6,  9, 12, 15])

In [34]:
arr > 3


array([ True, False, False,  True,  True])